package com.buildman.buildman.model;

public class Project_Images {

	int PROJECT_IMAGES_ID;
	String PROJECT_ID_PRJ_IMAGES;
	String SITE_ID_PRJ_IMAGES;
	String PRJ_EST_WORKMASTER_ID_PRJ_IMAGES;
	String PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES;
	String PATH_PRJ_IMAGES;
	String SYN_FLAG_PRJ_IMAGES;
	String IMAGES_CRAETION_DATE_PRJ_IMAGES;

	public int getPROJECT_IMAGES_ID() {
		return PROJECT_IMAGES_ID;
	}

	public void setPROJECT_IMAGES_ID(int PROJECT_IMAGES_ID) {
		this.PROJECT_IMAGES_ID = PROJECT_IMAGES_ID;
	}

	public String getPROJECT_ID_PRJ_IMAGES() {
		return PROJECT_ID_PRJ_IMAGES;
	}

	public void setPROJECT_ID_PRJ_IMAGES(String PROJECT_ID_PRJ_IMAGES) {
		this.PROJECT_ID_PRJ_IMAGES = PROJECT_ID_PRJ_IMAGES;
	}

	public String getSITE_ID_PRJ_IMAGES() {
		return SITE_ID_PRJ_IMAGES;
	}

	public void setSITE_ID_PRJ_IMAGES(String SITE_ID_PRJ_IMAGES) {
		this.SITE_ID_PRJ_IMAGES = SITE_ID_PRJ_IMAGES;
	}

	public String getPRJ_EST_WORKMASTER_ID_PRJ_IMAGES() {
		return PRJ_EST_WORKMASTER_ID_PRJ_IMAGES;
	}

	public void setPRJ_EST_WORKMASTER_ID_PRJ_IMAGES(String PRJ_EST_WORKMASTER_ID_PRJ_IMAGES) {
		this.PRJ_EST_WORKMASTER_ID_PRJ_IMAGES = PRJ_EST_WORKMASTER_ID_PRJ_IMAGES;
	}

	public String getPRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES() {
		return PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES;
	}

	public void setPRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES(String PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES) {
		this.PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES = PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES;
	}

	public String getPATH_PRJ_IMAGES() {
		return PATH_PRJ_IMAGES;
	}

	public void setPATH_PRJ_IMAGES(String PATH_PRJ_IMAGES) {
		this.PATH_PRJ_IMAGES = PATH_PRJ_IMAGES;
	}

	public String getSYN_FLAG_PRJ_IMAGES() {
		return SYN_FLAG_PRJ_IMAGES;
	}

	public void setSYN_FLAG_PRJ_IMAGES(String SYN_FLAG_PRJ_IMAGES) {
		this.SYN_FLAG_PRJ_IMAGES = SYN_FLAG_PRJ_IMAGES;
	}

	public String getIMAGES_CRAETION_DATE_PRJ_IMAGES() {
		return IMAGES_CRAETION_DATE_PRJ_IMAGES;
	}

	public void setIMAGES_CRAETION_DATE_PRJ_IMAGES(String IMAGES_CRAETION_DATE_PRJ_IMAGES) {
		this.IMAGES_CRAETION_DATE_PRJ_IMAGES = IMAGES_CRAETION_DATE_PRJ_IMAGES;
	}



public Project_Images(int PROJECT_IMAGES_ID, String PROJECT_ID_PRJ_IMAGES,
                      String SITE_ID_PRJ_IMAGES, String PRJ_EST_WORKMASTER_ID_PRJ_IMAGES,
					  String PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES, String PATH_PRJ_IMAGES,String SYN_FLAG_PRJ_IMAGES, String IMAGES_CRAETION_DATE_PRJ_IMAGES) {
	// TODO Auto-generated constructor stub
	this.PROJECT_IMAGES_ID=PROJECT_IMAGES_ID;
	this.PROJECT_ID_PRJ_IMAGES=PROJECT_ID_PRJ_IMAGES;
	this.SITE_ID_PRJ_IMAGES=SITE_ID_PRJ_IMAGES;
	this.PRJ_EST_WORKMASTER_ID_PRJ_IMAGES=PRJ_EST_WORKMASTER_ID_PRJ_IMAGES;
	this.PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES=PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES;
	this.PATH_PRJ_IMAGES=PATH_PRJ_IMAGES;
	this.SYN_FLAG_PRJ_IMAGES=SYN_FLAG_PRJ_IMAGES;
	this.IMAGES_CRAETION_DATE_PRJ_IMAGES=IMAGES_CRAETION_DATE_PRJ_IMAGES;

}
public Project_Images() {
	// TODO Auto-generated constructor stub
}
public Project_Images( String PROJECT_ID_PRJ_IMAGES,
						  String SITE_ID_PRJ_IMAGES, String PRJ_EST_WORKMASTER_ID_PRJ_IMAGES,
						  String PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES, String PATH_PRJ_IMAGES,String SYN_FLAG_PRJ_IMAGES, String IMAGES_CRAETION_DATE_PRJ_IMAGES) {
		// TODO Auto-generated constructor stub
		this.PROJECT_IMAGES_ID=PROJECT_IMAGES_ID;
		this.PROJECT_ID_PRJ_IMAGES=PROJECT_ID_PRJ_IMAGES;
		this.SITE_ID_PRJ_IMAGES=SITE_ID_PRJ_IMAGES;
		this.PRJ_EST_WORKMASTER_ID_PRJ_IMAGES=PRJ_EST_WORKMASTER_ID_PRJ_IMAGES;
		this.PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES=PRJ_EST_WORK_LOCATION_NAME_PRJ_IMAGES;
		this.PATH_PRJ_IMAGES=PATH_PRJ_IMAGES;
		this.SYN_FLAG_PRJ_IMAGES=SYN_FLAG_PRJ_IMAGES;
		this.IMAGES_CRAETION_DATE_PRJ_IMAGES=IMAGES_CRAETION_DATE_PRJ_IMAGES;

	}
	public Project_Images(int PROJECT_IMAGES_ID)
	{
		// TODO Auto-generated constructor stub
		this.PROJECT_IMAGES_ID=PROJECT_IMAGES_ID;
	}

}

